language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: ZDK2SgSLKMhVyO8FRJ+oCXkq98XytaRsvrgYejQRVvO61mUAZQiFOR/A1NXGkQw1JbwnC1QAH7J/wQwT5ewAHjrsqXYyDcOR32t1NHy9sMCboP/bD+klHAC5oMSmX38UxTbPmrBQOvwnxGeSCemcNrJCMYoEfwN6PcmZTKOFVgINsRhz0O4PmrKAkHBSIvY4rVp3PhgoQZUEnNU+D//P2cenAbySMu+vM87AsH7R76aP95IqKvABsZSNdJAbsdCy3p1DMXxkEbbm4HJQ7eRK6dhImrhCZJbXioa9fOVQdUu9ZUE1V+cRn8rCI96TP0FjiBsFVCmAKpieA//McuA+4JoY3fBgZO6GzB5bmCtN8Ns3LWemiKdCnjspHMG3Bkhl00It66I64674coQAuMZYi/K0s0XcZJdr3B/cS86aKWvUryLOSNsmXJMsKsvqcmIeS5guf7AzrocD2qAInkgLQjGpJ8T+SuwAYlxsgXEEOQUKyLt1DTN1v5Zc/wFtfZhY/mSGaSrZ04P+U7Mfz6slUHyLhh1tZXCWTCriEPTc3170+Tr8hdvCN9H529/3nt/l5rv11T8aKE1YrLEAXqsGl4EJ9MNkXesqvmN/0+dcbTGB+mWqmCeS+HCsQTrw3jyWiz/GAYiG5vYj3mCIBmPefqn5C2IF3fajsqA6HNLWOHI=
  app: progressive-team
